---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: default
spec:
  chart:
    spec:
      chart: jellyfin
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 6h0m0s
  values:
    env:
      TZ: America/Chicago
    hostNetwork: true
    image:
      repository: stiforr/jellyfin-ytmeta
      tag: 10.8.9
      pullPolicy: Always
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
        hosts:
          - host: &host jellyfin.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: jellyfin-tls
    persistence:
      media:
        enabled: true
        mountPath: /media
        accessModes: ReadWriteMany
        existingClaim: media-pvc
      config:
        enabled: true
        storageClass: "nfs-client"
      videos:
        enabled: true
        storageClass: "nfs-client-ssd"
        mountPath: /vids
        accessMode: ReadWriteMany
        existingClaim: media-pvc-ssd
        size: 250Gi
