---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-watcher
  namespace: default
spec:
  chart:
    spec:
      chart: k8s-watcher
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: komodorio
        namespace: flux-system
  interval: 6h0m0s
  values:
    existingSecret: k8s-watcher-secret
    watcher:
      actions:
        basic: true
        advanced: true
        podExec: true
      telemetry:
        enable: false
      clusterName: default
