---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sharry
  namespace: default
spec:
  chart:
    spec:
      chart: sharry
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 6h0m0s
  values:
    podAnnotations:
      configmap.reloader.stakater.com/reload: "sharry-config"
    persistence:
      database:
        enabled: true
        storageClass: nfs-client
        accessMode: ReadWriteOnce
        size: 20Gi
        mountPath: /data
    image:
      repository: eikek0/sharry
      tag: "v1.11.0"
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          nginx.ingress.kubernetes.io/client-body-buffer-size: "2048m"
          nginx.ingress.kubernetes.io/proxy-body-size: "2048m"
          nginx.ingress.kubernetes.io/proxy-buffering: "off"
        hosts:
          - host: &host sharry.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: sharry-tls
    config: |
      sharry.restserver {
        base-url = "https://sharry.${SECRET_DOMAIN}"
        logging {
          minimum-level = "Info"
        }
        bind {
          address = "0.0.0.0"
          port = {{ .Values.service.main.ports.http.port }}
        }
        backend {
          auth {
            fixed {
              enabled = true
              user = "admin"
              password = "admin"
              order = 10
            }
          }
          signup {
            mode = "open"
          }
          jdbc {
            url = "jdbc:h2:///data/sharry.db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE"
            user = "sa"
            password = ""
          }
        }
        webapp {
          chunk-size: "100M"
        }
      }
