---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sharry
  namespace: default
spec:
  chart:
    spec:
      chart: sharry
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 6h0m0s
  values:
    podAnnotations:
      configmap.reloader.stakater.com/reload: "sharry-config"
    persistence:
      config:
        enabled: true
        storageClass: nfs-client
    image:
      repository: eikek0/sharry
      tag: "v1.11.0"
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host sharry.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: sharry-tls
