apiVersion: v1
kind: Secret
metadata:
    name: plex-claim
type: Opaque
data:
    claim: ENC[AES256_GCM,data:jjC+JKFqjBTB7h5LfJtLTXjY7PjpL8v9Gjw=,iv:e/1mJTo/14+ej+N3ricxLRJ8iy7WLXDpO2iZLnxoIwk=,tag:uL2IAirA9kZZyuol12zAFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gpymng4jmuvlf2h3fupa95lptysdpagxz5f7qs8sr8zh2m9zpcqjgucdp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWmthSnh6UHNIWGoxUVkr
            QUdYUDIyQkxGZkZLMUJEUlEvaGlPUEl3TkhrCnpZaHNTMEZ3d3YraVdhbXpoRVVj
            UlRYMWZYbDVWeDB4K2paQ2N0MkV6bGsKLS0tIGU1ekNBMGdocllXcWNaN3VzTVZC
            UjdFaDAraDRGbFFOVEF3WWVLV2ZHT28KhQgHAUw71yAWRoQAKsN+yKDzyLJMm7wA
            YeTMz4wtlpHacEoIUKGrq4WgRri28J7XZQV5E21Q5cib6jHQvDviag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-17T14:15:45Z"
    mac: ENC[AES256_GCM,data:Icjj2vYVnByg720f9FiTzc1Rc99+DeBzjDZs7s6DyyUJ9s/3oDpEEGOJWwbrT5En/KfP2T2yD/2Ji74mk67Xmqz5qev+s+7tx3aSngKi1m0Wj5m3OAtO2ZXjPdDBcqO83hNvGYJZwc87X8v1CENPl6imvRi1LDyiVk9ac6uEe4o=,iv:c7wUTUvNB0uo24CK8e+mM8Ddn9Z5iDGGaPgKbYpI0CY=,tag:i5W8xPB8hRR/J1uG13JVAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
