apiVersion: v1
kind: Secret
metadata:
    name: plex-claim
    namespace: default
type: Opaque
data:
    claim: ENC[AES256_GCM,data:PAWEpRaglQd/rMquB4UihAzZbX1dQxM5VXAuLCxC8C0kBwJE,iv:JlLr0Oo9X4Pio4R0q5ipUVyj7Wj8gKEDZ8UKRFjq9Cc=,tag:hJSBUKR/Pvc8PTNL5sdNXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gpymng4jmuvlf2h3fupa95lptysdpagxz5f7qs8sr8zh2m9zpcqjgucdp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUm9RSm1hbjZ3Qm1YMnpl
            Snd0b1NYUjRFaXQvai82WjdFRFFEVlF0RGtNCnhoUVducWdRTklkYXhveVBSVkVO
            RmRKU0dSRDFxdVhlQWxDOVdTUy9naEEKLS0tIGlYa1VEbTcremJmZEZITGFSVFNq
            dWUxaS92Ykx5TFZITHIxM2tSN0lVaVkKCNFuKzF7vx4jrGgNC4MYuVMpZacB3nCv
            nCC9p/5LFIz7VHmg5mLElEMr+7vG3gkg3ZJD0K1j+fIxoHlgE0xOvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-17T14:23:10Z"
    mac: ENC[AES256_GCM,data:kENEJ6EN36ZLZAhdzZPkHwKH9ouRUm2U71202/Am0vm8Y+dmzOxfMCtj2G7Xze2R2KUMmshCGteuTHpUYGx3t1bIORf39Z8eOk4LTTDYf3s+fpud7n52zlejG0JwWmIcxF80QqVWH9n8zSKqJtCx1k4U0qhVrmzDsCN5xUPs6zo=,iv:ggHsfioiRboQeUul+8TtKdqBFUdh1+gHjlqoeHh2GQM=,tag:V2bKdvl0dZeANXfXKyxTWQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
