---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex-media-server
  namespace: default
spec:
  chart:
    spec:
      chart: plex
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: 6.4.3
  interval: 10m0s
  values:
    # nodeSelector:
    #   cpus: "24"
    service:
      main:
        enabled: true
        type: LoadBalancer
        primary: true
        ports:
          http:
            port: 32400
        externalTrafficPolicy: Local
    resources:
      # limits:
      #   cpu: 10000m
      #   memory: 3Gi
      requests:
        cpu: 1000m
        memory: 1Gi
    image:
      repository: ghcr.io/onedr0p/plex
      tag: 1.31.3.6868-28fc46b27
    env:
      TZ: America/Chicago
      PLEX_PREFERENCE_1: "FriendlyName=plex-kubernetes"
      PLEX_CLAIM: "claim-_6szWy_SDVsFj2Gb8jVy"
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/target: ipv4.${SECRET_DOMAIN}
          external-dns/is-public: "true"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
          nginx.ingress.kubernetes.io/server-snippets: |
            location / {
              proxy_set_header Upgrade $http_upgrade;
              proxy_http_version 1.1;
              proxy_set_header X-Forwarded-Host $http_host;
              proxy_set_header X-Forwarded-Proto $scheme;
              proxy_set_header X-Forwarded-For $remote_addr;
              proxy_set_header Host $host;
              proxy_set_header Connection "upgrade";
              proxy_cache_bypass $http_upgrade;
            }
          nginx.ingress.kubernetes.io/app-root: /web
        hosts:
          - host: &host plex.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: plex-tls
    persistence:
      media:
        enabled: true
        mountPath: /media
        storageClass: nfs-client-ssd
        accessModes: ReadWriteMany
        existingClaim: media-pvc-ssd
      config:
        enabled: true
        mountPath: /config
        storageClass: nfs-client-ssd
        accessModes: ReadWriteOnce
        size: 5Gi
