---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex-media-server
  namespace: default
spec:
  chart:
    spec:
      chart: plex
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: 6.4.3
  interval: 10m0s
  values:
    service:
      main:
        enabled: true
        type: LoadBalancer
        primary: true
        ports:
          http:
            port: 32400
      dnla-tcp:
        enabled: true
        type: LoadBalancer
        ports:
          dnla-tcp:
            enabled: true
            port: 32469
            protocol: TCP
            targetPort: 32469
        externalTrafficPolicy: Local
      dnla-udp:
        enabled: true
        type: LoadBalancer
        ports:
          dnla-udp:
            enabled: true
            port: 1900
            protocol: TCP
            targetPort: 1900
        externalTrafficPolicy: Local
    resources:
      limits:
        cpu: 2000m
        memory: 2Gi
      requests:
        cpu: 1000m
        memory: 1Gi
    image:
      repository: ghcr.io/k8s-at-home/plex
      tag: v1.29.2.6364-6d72b0cf6
    env:
      TZ: America/Chicago
      PLEX_PREFERENCE_1: "FriendlyName=plex-kubernetes"
      PLEX_CLAIM: "claim-6drbi4mkBUgo7N2HKXPx"
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/target: ipv4.${SECRET_DOMAIN}
          external-dns/is-public: "true"
          nginx.ingress.kubernetes.io/app-root: /web
        hosts:
          - host: &host plex.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: plex-tls
    persistence:
      media:
        enabled: true
        mountPath: /media
        storageClass: nfs-client
        accessModes: ReadWriteMany
        existingClaim: media-pvc
        subPath: plex
      config:
        enabled: true
        mountPath: /config
