---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex-media-server
  namespace: default
spec:
  chart:
    spec:
      chart: plex
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: 6.4.3
  interval: 10m0s
  values:
    image: ghcr.io/k8s-at-home/plex
    tag: v1.29.2.6364-6d72b0cf6
    env:
      TZ: America/Chicago
      PLEX_PREFERENCE_1: "FriendlyName=plex-kubernetes"
      PLEX_CLAIM: "claim-KErGJtQp_vJ-Max_716a"
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/target: ipv4.${SECRET_DOMAIN}
          external-dns/is-public: "true"
        hosts:
          - host: &host plex.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: plex-tls
    persistence:
      media:
        enabled: true
        mountPath: /media
        storageClass: nfs-client
        accessModes: ReadWriteMany
        existingClaim: media-pvc
        subPath: plex
      config:
        enabled: true
        mountPath: /config
