---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tubearchivist
  namespace: default
spec:
  chart:
    spec:
      chart: tubearchivist
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: stiforr
        namespace: flux-system
  interval: 6h0m0s
  install:
    remediation:
      retries: 30
  upgrade:
    remediation:
      retries: 30
  values:
    image:
      repository: bbilly1/tubearchivist
      tag: "v0.3.0"
    elasticsearch:
      security:
        existingSecret: tubearchivist-elasticsearch
    persistence:
      youtube:
        enabled: true
        existingClaim: media-pvc
        subPath: youtube
      config:
        enabled: true
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
        hosts:
          - host: &host tubearchivist.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: tubearchivist-tls
