apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
  namespace: default
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  mountOptions:
    - nolock
    - nfsvers=4.1
    - noacl
    - nocto
    - noatime
    - nodiratime
    - rsize=32768
    - wsize=32768
  nfs:
    path: /srv/nfs
    server: 192.168.1.178
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: default
spec:
  resources:
    requests:
      storage: 500Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
