---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tdarr
  namespace: default
spec:
  chart:
    spec:
      chart: tdarr
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 15m0s
  install:
    remediation:
      retries: 50
  upgrade:
    remediation:
      retries: 50
  values:
    image:
      repository: haveagitgat/tdarr
      tag: 2.00.18.2
    nodeSelector:
      cpus: "24"
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
        # nvidia.com/gpu: 1
      requests:
        cpu: 500m
        memory: 512Mi
    service:
      server:
        enabled: true
        primary: false
        type: LoadBalancer
        ports:
          server:
            enabled: true
            port: 8266
      main:
        ports:
          http:
            port: 8265
          server:
            enabled: false
    node:
      enabled: true
      id: node
      image:
        repository: haveagitgat/tdarr_node
        tag: 2.00.18.2
        pullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 12000m
          memory: 2Gi
        requests:
          cpu: 4000m
          memory: 1500Mi
    env:
      TZ: America/Chicago
      ffmpegPath: "tdarr-ffmpeg"
      PUID: "568"
      PGID: "568"
      THREADS_WORKER_INIT_TIMEOUT: "20000000"
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          hajimari.io/enable: "true"
        hosts:
          - host: &host tdarr.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: tdarr-tls
    persistence:
      shared:
        enabled: true
        mountPath: /shared
        type: pvc
        # storageClass: nfs-client
        accessMode: ReadWriteMany
        existingClaim: media-pvc
        subPath: shared
      config:
        enabled: true
        mountPath: /app/configs
        size: 1Gi
        accessMode: ReadWriteOnce
        storageClass: nfs-client
      data:
        enabled: true
        mountPath: /app/server
        size: 1Gi
        accessMode: ReadWriteOnce
        storageClass: nfs-client
      media:
        enabled: true
        mountPath: /media
        storageClass: nfs-client
        accessMode: ReadWriteMany
        existingClaim: media-pvc
      # preset:
      #   enabled: true
      #   mountPath: /app/presets
      #   type: configMap
      #   configMapName: tdarr-presets
      #   name: tdarr-presets
      #   readOnly: false
