---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tdarr
  namespace: default
spec:
  chart:
    spec:
      chart: tdarr
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 6h
  install:
    remediation:
      retries: 50
  upgrade:
    remediation:
      retries: 50
  values:
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      #   # Hardware acceleration using an Intel iGPU w/ QuickSync
      #   # These IDs below should be matched to your `video` and `render` group on the host
      #   # To obtain those IDs run the following grep statement on the host:
      #   # $ cat /etc/group | grep "video\|render"
      #   # video:x:44:
      #   # render:x:109:
      supplementalGroups:
        - 39
        - 105
    image:
      repository: haveagitgat/tdarr
      tag: 2.00.18.2
    resources:
      requests:
        cpu: 1000m
        memory: 2Gi
    service:
      server:
        enabled: true
        primary: false
        type: LoadBalancer
        ports:
          server:
            enabled: true
            port: 8266
      main:
        ports:
          http:
            port: 8265
          server:
            enabled: false
    node:
      enabled: true
      id: node
      image:
        repository: haveagitgat/tdarr_node
        tag: 2.00.18.2
        pullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 4000m
          memory: 1500Mi
    env:
      TZ: America/Chicago
      ffmpegPath: "tdarr-ffmpeg"
      PUID: "568"
      PGID: "568"
      THREADS_WORKER_INIT_TIMEOUT: "20000000"
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &host tdarr.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: tdarr-tls
    persistence:
      shared:
        enabled: true
        mountPath: /shared
      config:
        enabled: true
        mountPath: /app/configs
        size: 1Gi
        accessMode: ReadWriteOnce
        storageClass: nfs-client
      data:
        enabled: true
        mountPath: /app/server
        size: 1Gi
        accessMode: ReadWriteOnce
        storageClass: nfs-client
      media:
        enabled: true
        mountPath: /media
        storageClass: nfs-client
        accessMode: ReadWriteMany
        existingClaim: media-pvc
      vids:
        enabled: true
        mountPath: /vids
        storageClass: nfs-client-ssd
        accessMode: ReadWriteMany
        existingClaim: media-pvc-ssd
        size: 250Gi
