---
kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 192.168.1.150
        k8s-1:
          ansible_host: 192.168.1.149
        k8s-2:
          ansible_host: 192.168.1.151
