---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Chicago
  METALLB_LB_RANGE: 192.168.1.149-192.168.1.241
  METALLB_K8S_GATEWAY_ADDR: 192.168.1.232
  METALLB_INGRESS_ADDR: 192.168.1.150
