# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:/W8H3mfIlczFd6E=,iv:0ud9M6sg2egCQ7upY8PEn5xuE3rd5Hqax0Ss1jvR9V4=,tag:2RB3EpEqiA96OW4mt0tbmg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:aRo81sHxbgAsYL7gAsowhkNoloJJIQ==,iv:3ziX6qC0JmZB8Jw0mrhg9IY2+ak/fM3a41irTiek7IA=,tag:vOyRXmC2OxwmclM/Am/wWw==,type:str]
    PLEX_TOKEN: ENC[AES256_GCM,data:qcOgyAnPh/Yw2B1wIAhKKvKiJ0lBP3gOisA7hA==,iv:fpFjSjNoOLxIkq0Uu7zGs6bDUGFITr7LyvSTONq7D8k=,tag:2uQKGo4rdJpck3e4yqsfzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gpymng4jmuvlf2h3fupa95lptysdpagxz5f7qs8sr8zh2m9zpcqjgucdp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYWxzNENpTjFnbnNEbTJs
            UXBOdkFVTnVYK3RSM2NTUVExMmtzZzZSQlgwCnZJU1E3LzY4VlUyblYzTHVuc3RZ
            aWF4WE1EOTU5c3NlTFpmOFMyRk1mM28KLS0tIHc4UUpBVHlGMmsrRFNwSmRiemJW
            RmdvU0oyd3VERXpUN2kyV1B5aURXUVEKBW3kquguxbnnCFTAMQCYeyTtUOH92cYw
            SQis2kKac7dubXNnrJZAKRkTdhZejcXQRcGW1RCQrRQMvjrxlQNOvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-15T23:26:01Z"
    mac: ENC[AES256_GCM,data:J/9Z7aGF37AqeMDhN3cOanVG2LW7MoR5hMZdnIiYAgMRS2td0GcJrUrgW3i27FYCcujFrVGp1EJcA+HdfjN6LSSr9lsoBoElWMG9JttwiwjgSsYJX0GKXbb6MCsJ0XGGUI1Jw8yBXUigLOWosGSQkz0U2G2bJMIpENX3MhNbcyw=,iv:pAIQhQ0giSytM0jkiSQuQeOMgCIVxuW6vCs5lrE/6GY=,tag:HVakNIJnQfDkynbRNAfeFg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
