apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:1oHE6n7GVv6LvnMYqdwnQbqhXgU7Yxv22irbYfJMKsDcfbFHRSApnKyb85EkvxK42c3ch1Gir8goJS/X5zSXb9eA42SGQMRYVIaJTLQ87/2ACOvpBgpfBf2sxdNK/bIhfo0L7kjrUGNgq1C4DYSdlYaWsPpeliITTCNvoXbYnqRtEqj230ZTKvzipRyKANpyHj5ix0iUZKMDCSkXzLgEvUhFwUjjotC6kz3P3Zc2iblrqAr4pPRs5XIeBY4yzcsRD3uc/XIE0MbTu65pspJmRHFNcrcVUO4r,iv:Ts6Hu6aF3umPXg2yT0d4DIqcYSNWoZTRRs9kSXPDmmU=,tag:S5q4zqYef+xSh6dUE1jodQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gpymng4jmuvlf2h3fupa95lptysdpagxz5f7qs8sr8zh2m9zpcqjgucdp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UnkrY3V6dUdkZjBuL1hO
            Nk5pcFZlTWozTGtDc3JJMi9ubWlXWnZuQlVvClE2b29RMnQ5aTBRcmNsMVpPUzM1
            YldiaHNKY29hYzVIb0MxamVaaWY1STAKLS0tIEJqZTFQY0ZkRmFZSlhBZjBLd3du
            RksvVS84L2FtWXlOQkh3VXlWKzlRY3cK7N7IMOerNWhGomLQdXe4GJdOMsQTcoR9
            TYK1fIFHOdWS46j2GNHNCpZTd4WrO7YHF2WOTMTVR+4VlHEyGgqiJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-16T22:07:53Z"
    mac: ENC[AES256_GCM,data:P+tZis8eYgaUXVOThc7HP2Qz8Jr0pCKzrisf/9HOSX4LPZReUAuz7m3oV1OcVOw3N8gPaHDoavYs1Iz1lXk4sOIeA2jFO98taiSl04RLBXwUSLAkCpYGL3/T5VesFGpgg9C/zJLsJ+DuEm6dmjiKUf0+jW21mI7rgcaf21TZGcA=,iv:frFvJemnZfrL6xAuztHhu11BJuHzvGflliELS7FTVGk=,tag:oGGzgUDxypLU5QoAvA1r8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
