---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  chart:
    spec:
      chart: grafana-loki
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    remediation:
      retries: 50
  upgrade:
    remediation:
      retries: 50
  interval: 6h0m0s
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
