kind: Secret
ansible_user: ENC[AES256_GCM,data:0WNeJqXVVg==,iv:hopEwe0IfYEioTjOHvBOZsE0ghDbXHVAqAv/LcA2XBQ=,tag:VnG5pvwlLyOLDNNUkAqczw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:8jdg79QuhhwJ,iv:wtPPVxeYDYj3Ks3rij3fDAm9kMfKevU+wmUToDgh/ZY=,tag:gORDavAkxX2PIMlgWg+HOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gpymng4jmuvlf2h3fupa95lptysdpagxz5f7qs8sr8zh2m9zpcqjgucdp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2eCt3c3k3eGp1blRvUFJK
            TlZ3Yzg3R1ZHREkyNFl6cURYczl2TGFybGtVClQ4VjNxUUpWNXJWbjlLZFdNUWJZ
            Qk5ZbzJ2RGYxZEpEUjN1NzR0ZlZmamcKLS0tIGxic2dIeHZnMThKN1RIeXdXNGRK
            a3RpbHQ0bzhYUGxQNkhGaGVJUmZldTgKG9g3FwWulp/r65ATIXeRvu7Ip1siyCIU
            tiNYA3S+wdYt62N+KHf1sTh4Fsr1l06GGaktTlpbsGdwl7iabgvRDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-15T16:06:04Z"
    mac: ENC[AES256_GCM,data:uQSBIiGXqq50GAEpLi2ghBL65SVfcvJ7IPbSnO9/p+YtZeqjEi3TTWF6QUphdrrDXqeVTpuBVtwVpiQ9gdn36UtvhKE/OUy37wPMynclZL3VWiqe9sdl1tQVesjBipYwMNVF/+7HaymvPytHDarRCW59BTrH9iB4puyebB3YnvI=,iv:aQ+VxXaS5hSQRqEwz67ewrYo7n50ucsG77kQDKY/L6w=,tag:9FVtYBtWPcuUjOvzaDI1kw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
