---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reloader
  namespace: kube-system
spec:
  interval: 6h
  chart:
    spec:
      chart: reloader
      version: v0.0.129
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: flux-system
      interval: 6h
  install:
    createNamespace: true
    remediation:
      retries: 50
  upgrade:
    remediation:
      retries: 50
  values:
    fullnameOverride: reloader
