---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: youtubedl-material
  namespace: default
spec:
  chart:
    spec:
      chart: youtubedl-material
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 6h0m0s
  values:
    image:
      repository: ghcr.io/tzahi12345/youtubedl-material
      tag: nightly-2023-03-07
    env:
      TZ: America/Chicago
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hosts:
          - host: &host youtubedl.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: youtubedl-tls
    persistence:
      config:
        enabled: true
        mountPath: /app/appdata
        storageClass: nfs-client-ssd
      audio:
        enabled: true
        mountPath: /app/audio
        accessMode: ReadWriteMany
        storageClass: nfs-client
        size: 10Gi
      subscriptions:
        enabled: true
        mountPath: /app/subscriptions
        accessMode: ReadWriteMany
        storageClass: nfs-client
        size: 10Gi
      users:
        enabled: true
        mountPath: /users
        accessMode: ReadWriteOnce
        storageClass: nfs-client-ssd
        size: 1Gi
      video:
        enabled: true
        mountPath: /app/video
        existingClaim: media-pvc-ssd
        subPath: youtube/video
        accessMode: ReadWriteMany
