---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-networking
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./cluster/apps/networking
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
  dependsOn:
    - name: config
    - name: charts
  decryption:
    provider: sops
    secretRef:
      name: sops-age
