---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-default
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./cluster/apps/default
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  dependsOn:
    - name: config
    - name: charts
    - name: apps-storage
    - name: apps-networking
    - name: apps-system
    - name: apps-monitoring
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
  decryption:
    provider: sops
    secretRef:
      name: sops-age
