---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  chart:
    spec:
      chart: home-assistant
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 15m0s
  install:
    remediation:
      retries: 30
  upgrade:
    remediation:
      retries: 30
  values:
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2022.12.0
    env:
      TZ: America/Chicago
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/target: ipv4.${SECRET_DOMAIN}
          external-dns/is-public: "true"
          nginx.org/websocket-services: home-assistant
        hosts:
          - host: &host home-assistant.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: home-assistant-tls
    persistence:
      config:
        enabled: true
        storageClass: "nfs-client"
    postgresql:
      enabled: true
      image:
        repository: bitnami/postgresql
        tag: 14.1.0
      auth:
        database: home-assistant
        existingSecret: home-assistant-postgresql
        secretKeys:
          adminPasswordKey: postgres-password
          userPasswordKey: password
          replicationPasswordKey: replication-password
      primary:
        persistence:
          enabled: true
          storageClass: "nfs-client"
