apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-postgresql
    namespace: default
type: Opaque
data:
    postgres-password: ENC[AES256_GCM,data:ZMN4+Cv3YA+qDbxb8X9ObrHqjAKphAkxEkrszc3Onl8+NyCwTO5hVyzQXV8=,iv:jy37zQ4ZvkdQxT89wWHhXUjWdx+Kh2PoHEP72H+mJ+I=,tag:1TqNYpv3nyVrBv45E+qL5w==,type:str]
    password: ENC[AES256_GCM,data:nCw5ymSG12U7eMEwz9pyOvn1YMvyc0DUUKnpTV/v1ZMXZrU13No8SQ9Fy60=,iv:5A/aLO/6NG7tJJOxGmCpdnSi9mrME+UvlcFyqHdKTik=,tag:Cjs7dMcvZSemCZ9u8DSsiw==,type:str]
    replication-password: ENC[AES256_GCM,data:e9FQCqo9LGPu0NJseE+6cx/Lk5jv2KN8fKrWZJxSUaPo4el9kI4jXiYxzLo=,iv:SPRKNQqF/wfh89uko4bcROa7tP6xua4inAe9ZfUbEzM=,tag:+dCOqtIQsScd7tgkc3rkMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gpymng4jmuvlf2h3fupa95lptysdpagxz5f7qs8sr8zh2m9zpcqjgucdp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RXZpU0V5dXRNQ3FQTXpB
            VmdZMEdpZG8wU3VrZFppY2pqcW5tUmpJWkZnClAxelFjR1pDSXZuVHFvcUpKMTUv
            TXhPZ3k3ZzF1TG5aemFzOTlhZS82MFkKLS0tIFZvQ01MaW5ZcHdON2tNa1RrT2pz
            bzlhenlibFZhZWlJeEludm9waGxxbTAKbJwj/ksjgI/+aii76ZmU1hXAVQgbMx2C
            x1IPiG16rjP6USFrXMxYNSqJ+xj52PIvkl2XzMUybJ1fsFZ1l/bcyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-15T16:01:49Z"
    mac: ENC[AES256_GCM,data:XVWoEM7lW68wSMGvoxb9AhAlUueZHzb2myfpXEe798g9ERjoFPY4EkdeUOlwSaDcigHBuZLR57NyRBaBCd9k+x3LjdoifUZsBEiNHLFKmBBnN6Jlpma9whoA9LBed1f+WiiP+QX5y2QXX4U8a5f7RIB6owbO5VsMfa+tBOXS8Iw=,iv:64ZI8SKVu16EUH0rwg5v98TzqpF1iWJfikrfCbvV0Jo=,tag:oY+ku+v1Qjdj1Biowx3gRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
