---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: default
data:
  bookmarks.yaml: |
    ---

  docker.yaml: |
    ---

  kubernetes.yaml: |
    ---
    mode: cluster

  services.yaml: |
    ---
    - Development:
        - Gitea:
            icon: gitea.png
            href: https://gitea.${SECRET_DOMAIN}
            description: Private Github Alternative
            app: gitea
            namespace: dev
        - Drone CI:
            icon: drone.png
            href: https://drone.${SECRET_DOMAIN}
            description: CI/CD Platform
            app: drone
            namespace: dev

  settings.yaml: |
    ---

  widgets.yaml: |
    ---
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true

    - search:
        provider: duckduckgo
        target: _blank
