---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: default
data:
  bookmarks.yaml: |
    ---

  docker.yaml: |
    ---

  kubernetes.yaml: |
    ---
    mode: cluster

  services.yaml: |
    ---
    - Media:
      - Plex:
          href: https://plex.${SECRET_DOMAIN}
          icon: plex.png
          app: plex
          namespace: default
          widget:
            type: plex
            url: https://plex.${SECRET_DOMAIN}
            key: ${PLEX_TOKEN}
      - Overseer:
          href: https://overseer.${SECRET_DOMAIN}
          icon: overseer.png
          app: overseer
          namespace: default
          widget:
            type: overseer
            url: https://overseer.${SECRET_DOMAIN}
            key: ${OVERSEER_TOKEN}
      - Radarr:
          href: https://radarr.${SECRET_DOMAIN}
          icon: radarr.png
          app: radarr
          namespace: default
          widget:
            type: radarr
            url: https://radarr.${SECRET_DOMAIN}
            key: ${RADARR_TOKEN}
      - Sonarr:
          href: https://sonarr.${SECRET_DOMAIN}
          icon: sonarr.png
          app: sonarr
          namespace: default
          widget:
            type: sonarr
            url: https://sonarr.${SECRET_DOMAIN}
            key: ${SONARR_TOKEN}

  settings.yaml: |
    ---

  widgets.yaml: |
    ---
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true

    - search:
        provider: duckduckgo
        target: _blank
