---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: default
data:
  bookmarks.yaml: |
    ---

  docker.yaml: |
    ---

  kubernetes.yaml: |
    ---
    mode: cluster

  services.yaml: |
    ---
    - Home:
      - Adguard:
          href: https://home-assistant.stiforr.com/a0d7b954_adguard/dashboard
          icon: adguard.png
          widget:
            type: adguard
            url: https://192.168.1.136:8123/a0d7b954_adguard/dashboard
            username: ${ADGUARD_USERNAME}
            password: ${ADGUARD_PASSWORD}
      - Proxmox:
          href: https://192.168.1.175:8006
          icon: proxmox.png
          widget:
            type: proxmox
            url: https://192.168.1.175:8006
            username: ${PROXMOX_USERNAME}
            password: ${PROXMOX_PASSWORD}
    - Media:
      - Overseerr:
          href: https://overseerr.${SECRET_DOMAIN}
          icon: overseerr.png
          app: overseerr
          namespace: default
          widget:
            type: overseerr
            url: http://overseerr:5055
            key: ${OVERSEER_TOKEN}
      - Radarr:
          href: https://radarr.${SECRET_DOMAIN}
          icon: radarr.png
          app: radarr
          namespace: default
          widget:
            type: radarr
            url: http://radarr:7878
            key: ${RADARR_TOKEN}
      - Sonarr:
          href: https://sonarr.${SECRET_DOMAIN}
          icon: sonarr.png
          app: sonarr
          namespace: default
          widget:
            type: sonarr
            url: http://sonarr:8989
            key: ${SONARR_TOKEN}

  settings.yaml: |
    ---

  widgets.yaml: |
    ---
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true

    - search:
        provider: duckduckgo
        target: _blank
