---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: default
data:
  bookmarks.yaml: |
    ---

  docker.yaml: |
    ---

  kubernetes.yaml: |
    ---
    mode: cluster

  services.yaml: |
    ---
    - Media:
      - Plex:
          href: https://plex.${SECRET_DOMAIN}
          icon: plex.png
          app: plex
          namespace: default
          widget:
            type: plex
            url: http://plex-media-server:32400
            key: ${PLEX_TOKEN}
      - Overseerr:
          href: https://overseerr.${SECRET_DOMAIN}
          icon: overseerr.png
          app: overseerr
          namespace: default
          widget:
            type: overseer
            url: http://overseer:5055
            key: ${OVERSEER_TOKEN}
      - Radarr:
          href: https://radarr.${SECRET_DOMAIN}
          icon: radarr.png
          app: radarr
          namespace: default
          widget:
            type: radarr
            url: http://radarr:7878
            key: ${RADARR_TOKEN}
      - Sonarr:
          href: https://sonarr.${SECRET_DOMAIN}
          icon: sonarr.png
          app: sonarr
          namespace: default
          widget:
            type: sonarr
            url: http://sonarr:8989
            key: ${SONARR_TOKEN}

  settings.yaml: |
    ---

  widgets.yaml: |
    ---
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true

    - search:
        provider: duckduckgo
        target: _blank
