---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homepage
  namespace: default
spec:
  chart:
    spec:
      chart: homepage
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: flux-system
  interval: 6h0m0s
  values:
    image:
      repository: ghcr.io/jameswynn/homepage
      tag: kubernetes
    controller:
      strategy: RollingUpdate
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
    serviceAccount:
      name: homepage
      create: true
    enableRbac: true
    ingress:
      main:
        enabled: true
        labels:
          gethomepage.dev/enabled: "true"
        annotations:
          gethomepage.dev/name: "Homepage"
          gethomepage.dev/description: "A modern, secure, highly customizable application dashboard."
          gethomepage.dev/group: "A New Group"
          gethomepage.dev/icon: "homepage.png"
        ingressClassName: "nginx"
        hosts:
          - host: &host "homepage.local"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: homepage-tls
    config:
      useExistingConfigMap: homepage-config
