apiVersion: v1
kind: Service
metadata:
  name: project-ozone
  namespace: default
spec:
  ports:
    - port: 25565
      targetPort: 25565
      protocol: TCP
---
kind: Endpoints
apiVersion: v1
metadata:
  name: project-ozone
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.1.147
    ports:
      - port: 25565
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-ozone
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/target: ipv4.${SECRET_DOMAIN}
    external-dns/is-public: "true"
spec:
  rules:
    - host: po3.stiforr.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: project-ozone
                port:
                  number: 25565
