---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello-free-shavacado
  namespace: default
spec:
  chart:
    spec:
      chart: hello-free-shavacado
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: stiforr
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 50
  upgrade:
    remediation:
      retries: 50
  interval: 6h0m0s
  values:
    image:
      repository: stiforr/hello-free-shavacado-new
      tag: develop-d00c7cc25c5c576a1195f8dade1fe114ab80395a
      pullPolicy: IfNotPresent
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
        hosts:
          - host: &host hello-free-shavacado.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: hello-free-shavacado-tls
    secrets:
      config:
        enabled: false
