apiVersion: v1
kind: Secret
metadata:
    name: openvpn-auth-secret
    namespace: default
data:
    VPN_AUTH: ENC[AES256_GCM,data:m8GSkH05NIIl4McwE4qaUKsN9Yx1FUwS2Di5yA==,iv:Tq8DOdlnMp/GZTdiGrxi5IU88RkPOAEePioUrOx4r/o=,tag:oHkKbvzGUws+4AaMpQeUCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gpymng4jmuvlf2h3fupa95lptysdpagxz5f7qs8sr8zh2m9zpcqjgucdp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFR0tkTjE5N0hHNGsrVkwy
            ajdKeGhQMzRac29UOHBFcGk3bXdMbTZ0QXhzCnZwVUZ3Zzk2RGRkQk5NdWtQQnlo
            QVcxcmZvL2FKVG9rcU9IV1NMZVFka0UKLS0tIHc2bUZMNVNTSThOZWcwamhtdVA3
            WWtiazhIYzFjakRRKzFEVWJtVXFod0UK7oJN2SmG3IgJ/pCTvMKu/qBYeu7b0Uwt
            Sf9nCJ39pW5bJoB+Fr4nQ2J96SExTeKtJyBCJlOdS3cnPsAlQwJr/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-15T23:19:44Z"
    mac: ENC[AES256_GCM,data:4dyX/5OGDCgblXCPX678Klrk4TB5a+055g81qLnbVcTl8wOUzt70axMB/r7u/YDQAWHC3f2wKL4HQURjnPiXK+cxHj+oltSyuS2ZR58LOJ9OR331OlAj1F8Kqsb9FWNY44dLQINOxur717T7SVPzXAUdCvMlD8ntkw2NuE5X7yg=,iv:XfqtGtIv3PVCBWL7rNF5Eg+PxU1LehdusO4mkEn4w5w=,tag:emlBuWEU7j9B5sCrzQbZPA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
