---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: default
spec:
  chart:
    spec:
      chart: qbittorrent
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: 13.5.2
  interval: 10m0s
  values:
    env:
      TZ: America/Chicago
      WAIT_FOR_VPN: true
    image:
      repository: ghcr.io/onedr0p/qbittorrent
      tag: 4.4.5
    probes:
      startup:
        enabled: false
      liveness:
        enabled: false
      readiness:
        enabled: false
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          hajimari.io/enable: "true"
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.1.0/16"
          nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        hosts:
          - host: &host qbittorrent.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: qbittorrent-tls
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
    persistence:
      downloads:
        enabled: true
        mountPath: /downloads
        size: 1Gi
        storageClass: nfs-client
        accessModes: ReadWriteMany
        existingClaim: media-pvc
        subPath: downloads
      media:
        enabled: false
      shared:
        enabled: true
        type: emptyDir
        mountPath: /shared
    addons:
      vpn:
        enabled: true
        env:
          FIREWALL: "off"
        type: openvpn
        openvpn:
          image:
            repository: dperson/openvpn-client
            tag: latest
          authSecret: openvpn-auth-secret
        configFileSecret: openvpn-config
        scripts:
          up: |-
            #!/bin/bash
            /etc/openvpn/up.sh
            echo "connected" > /shared/vpnstatus

          down: |-
            #!/bin/bash
            /etc/openvpn/down.sh
            echo "disconnected" > /shared/vpnstatus
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - if [ $(curl -s https://ipinfo.io/region) != 'Florida' ]; then exit 0; else exit $?; fi
            initialDelaySeconds: 30
            periodSeconds: 60
            failureThreshold: 1
