apiVersion: v1
data:
    vpnConfigfile: ENC[AES256_GCM,data:ap2Bx/zBu1A9EwON2d/SzoDnwRywnAjHlj5ESNztJkIU1ohXLyp5oArsTh018LowQ31uecnrulNPeu9KTwF8/QdsWjz1Zvo/NSieZoM6ZXEyhDNZMn4OXY3ZOUlhqvKl80IeLqp9cXZFuSBmtN28nAbAjKguOJ5VWdd4hgebKSV0GhZz2Q8m1bSTaiOPFh3JYPnlK8X5TGYoCFHLgQRvnvnuuM02LO03dtLUomo1bhBUpxDOlT/yoznkEVh7hhW6YvKEBqySW2FLNsF8R54kguuve2U2G4rT8MKm006irvCknghp+LRDzYjGO4aOx+x6DwYWqaMsQr+uiQSLxTLhhYxQEBTlG+NiJWt7Qn1oprNOFBe/BY/NhnUUkNaoiqtqrRRO9qWDeT+3jYZ3Y7FvPwKni8/+pDMUDAZHnaNCZEuwXNyqqqmXljSpMSLUGXPKCVsU7JrYLpGJ+LYx2fCHazzN6HU=,iv:ki7RAxG7tmd4zYVh4u9xXQuMSWb367FTKdfqSBc7TUs=,tag:gp1gfDB5XgU++YgwVzWcoA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: wireguard-config
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gpymng4jmuvlf2h3fupa95lptysdpagxz5f7qs8sr8zh2m9zpcqjgucdp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQb0prZWZGRUJLVlQ1MnFo
            UHE0WlZpcnZTSXBRYVZMaGdneFp6REszeG1VCkxoWms1eFpDcWRqdVdLSnVpSFNU
            VnlNcFRHU01pSjMrK2FpbWJUQ0VyUVEKLS0tIDZSQitXUnBIekdCWnF2dkJaMEht
            R3FLUnFQNmFheGUrUHdmZG1ESHVyU00KANhTHKC9s/vOFeJWFGcuFHt3l3nPP6DV
            9N0CZ95KdY2Eo7DgbUJa/T7MIuQnvqbI8zGsw/WbKY6Uk7Ixk8zWMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-17T19:18:43Z"
    mac: ENC[AES256_GCM,data:cp57hKYtWTjOwOjWlOyTxi2k3HhzarT/i5bCuVTcdPrJ8TVrn8FT8XXULm3vnWAzXF6QZOUmAH723uBYxwlsAOaT1dEJXe9FB2tBo0i8YKLA26Y6MzgJq1bUSm0eMVraan3gJj/bYStkk+ZHGN4iETUV4qm9WZnmW52cIOzy0Wk=,iv:ecL1St6D5ZpkwPAHNWNTzPonS+YEKi6Dfc97aukioJc=,tag:Y2WbRT70/oeUYGWr6/AYlQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
