---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dashy
  namespace: default
spec:
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 6h0m0s
  values:
    command: ["/bin/sh"]
    args:
      - -c
      - |
        [[ -f /app/public/conf.yml ]] || cp /tmp/conf.yml /app/public/conf.yml && \
        yarn build-and-start
    global:
      fullnameOverride: dashy
    image:
      repository: ghcr.io/lissy93/dashy
      tag: 2.1.1
      pullPolicy: IfNotPresent
    service:
      main:
        ports:
          http:
            port: 80
    configMap:
      config:
        enabled: true
        data:
          conf.yml: |
            {{- .Files.Get "conf.yml" | nindent 4 }}
    persistence:
      data:
        enabled: true
        mountPath: /app/public
        size: 1Gi
        storageClass: nfs-client-ssd
        type: pvc
        accessMode: ReadWriteMany
      config:
        enabled: true
        type: configMap
        subPath: conf.yml
        name: dashy-config
        items:
          - key: conf.yml
            path: conf.yml
        mountPath: /tmp/conf.yml
        storageClass: nfs-client-ssd
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/target: ipv4.${SECRET_DOMAIN}
        hosts:
          - host: dashy.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - dashy.${SECRET_DOMAIN}
            secretName: dashy-tls
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
