---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dashy
  namespace: default
spec:
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 6h0m0s
  values:
    global:
      fullnameOverride: dashy
    image:
      repository: ghcr.io/lissy93/dashy
      tag: 2.1.1
      pullPolicy: IfNotPresent
    service:
      main:
        ports:
          http:
            port: 80
    persistence:
      config:
        enabled: true
        mountPath: /app/public/conf.yml
        type: configMap
        storageClass: nfs-client-ssd
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/target: ipv4.${SECRET_DOMAIN}
        hosts:
          - host: dashy.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - dashy.${SECRET_DOMAIN}
            secretName: dashy-tls
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
