---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
spec:
  chart:
    spec:
      chart: keda
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: keda
        namespace: flux-system
  interval: 6h0m0s
  values:
    metricsServer:
      replicaCount: 0
    prometheus:
      operator:
        enabled: true
        podMonitor:
          enabled: true
          interval: 30s
          namespace: keda
