---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: default
spec:
  chart:
    spec:
      chart: radarr
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: 16.3.2
  interval: 6h
  install:
    remediation:
      retries: 30
  upgrade:
    remediation:
      retries: 30
  values:
    env:
      TZ: America/Chicago
      PUID: 1000
      PGID: 1000
    image:
      repository: lscr.io/linuxserver/radarr
      pullPolicy: IfNotPresent
      tag: version-4.4.4.7068
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          hajimari.io/enable: "true"
        hosts:
          - host: &host radarr.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: radarr-tls
    # podSecurityContext:
    #   runAsUser: 1000
    #   runAsGroup: 1000
    persistence:
      downloads:
        enabled: false
        mountPath: /downloads
        storageClass: nfs-client
        accessModes: ReadWriteMany
        existingClaim: media-pvc
        subPath: downloads
      config:
        enabled: true
        storageClass: nfs-client
      media:
        enabled: true
        mountPath: /media
        storageClass: nfs-client
        accessModes: ReadWriteMany
        existingClaim: media-pvc
      vids:
        enabled: true
        mountPath: /data
        storageClass: nfs-client-ssd
        accessMode: ReadWriteMany
        existingClaim: media-pvc-ssd
        size: 250Gi
