---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: default
spec:
  chart:
    spec:
      chart: radarr
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: 16.3.2
  interval: 15m0s
  install:
    remediation:
      retries: 30
  upgrade:
    remediation:
      retries: 30
  values:
    env:
      TZ: America/Chicago
    image:
      repository: ghcr.io/onedr0p/radarr
      pullPolicy: IfNotPresent
      tag: 4.2.4.6635
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          hajimari.io/enable: "true"
        hosts:
          - host: &host radarr.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: radarr-tls
    persistence:
      downloads:
        enabled: false
        mountPath: /downloads
        existingClaim: media-pvc
        storageClass: nfs-client
        subPath: downloads
      config:
        enabled: true
      media:
        enabled: true
        mountPath: /media
        storageClass: nfs-client
        accessModes: ReadWriteMany
        existingClaim: media-pvc
